# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Edward Shen
email: edward@syllogism.xyz
description: A landing page for me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://syllogism.xyz"
twitter_username: _EdwardShen
github_username:  edward-shen

# Build settings

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - reference
  - run_server.sh
